car = 'Honda'
plant = 'sunflower'
name = 'marie'
dinosaur = 'stegosaurus'
handheld = '3ds'
age = 16

print("Oh? Is that car of toyota.")
print(f"{car == 'toyota'}, you have a terribly narrow view of cars...")
print("Wow! So you have a honda city?")
print(f"{car.lower() == 'honda'}. Eyyyyy?! How did'ja know. Even i couldn't guess...")
print("It's kinda obvious when it's literally written on the back of the car.")
print("WHAT?! That's the last place anyone would check...")
print("correction = you would check")
print("-On the way to school-")
print("That rose looks so beautiful...")
print(f"{plant == 'rose'}, dumbass! It's a sunflower.")
print(f"{plant == 'sunflower'}, i didn't notice. ALSO, I'M NOT DUMB!!!")
print("Says the guy who can't distinguish between anything!")
print("-in school, during lunch-")
print("ARE YOU A JESSICA?! You totally look like a jessica...")
print("um...")
print(f"{name == 'jessica'}, dumbass!. She looks more like a marie!")
print(f"{name == 'marie'}, i'm marie...")
print("Nyahahaha!")
print("-at a sleepover-")
print("FALCON PUNCH!!! Oh, you have dinosaur toys!")
print("Yeah, look at this ankylosaurus i have!")
print("HEHEHHEHEHE! For once, i  can say, with confidence,")
print(f"{dinosaur == 'ankylosaurus'}!!!, it is a stegosaurus!.")
print("No way... you can't just break the hierarchy like that! I'M SUPPOSED TO ALWAYS BE RIGHT!")
print(f"It is {dinosaur == 'stegosaurus'}, Mr. I am always right and you are wrong!")
print("According to my extensive knowledge of dinosaurs which cannot be compared to,")
print("This is indeeed a stegosaurus!")
print("Now we are equ-")
print("No. No we are not. You cannot distinguish between flowers.")
print("Meanwhile, i cannot distinguish between 'dinosaurs'. We are not equal.")
print("- 15 minutes later, before sleeping -")
print("You have a ds as well?!")
print(f"{handheld == 'ds'}, dumbass!, it's a 3ds.")
print(f"OHH! That new one! {handheld == '3ds'}, it looks identical!")
print("No, no it doesn't. You truly are hopeless... i mean, a dumbass.")
print("-after maths test-")
print("hrmmm, let's see how many i got right:")
print(f"{age == 15}, {age != 16}, {age < 15}, {age > 17}, {age <= 1}, {age >= 50}")
print("This test was a total sweep, i got all of them right:")
print(f"{age == 16}, {age != 1}, {age < 17}, {age <= 17}, {age > 1}, {age >= 1}")
print("Ohhh, dumbass! Looks like your a bigger idiot than i thought.")
print("NO! This test was too difficult!")
print("You mean, for a plant?")
print("WHO CARES ANYWAY!!! I'M GOING TO A SPORTS UNIVERSITY ANYWAY!")
print("I highly doubt that considering all the F's your gonna inevitably get in your result card.")
print(f"These questions where you got {age == 15 and age < 1} and {age <= 15 or age < 1} were the easiest ones as well...")
print(f"They were obviously {age == 16 and age < 17} and {age == 16 or age < 17}!")