rivers = ['indus', 'jhelum', 'chenab', 'ravi', 'sutlej', 'beas']
print(rivers)
sorted(rivers)
print(rivers)
sorted(rivers, reverse = True)
print(rivers)
rivers.reverse()
print(rivers)
rivers.reverse()
print(rivers)
rivers.sort()
print(rivers)
rivers.sort(reverse = True)
print(rivers)
print(len(rivers))
del rivers[0]
print(rivers)
rivers.remove('ravi')
print(rivers)
river = rivers.pop()
print(rivers)
rivers[0] = 'zhob'
rivers.append('dasht')
rivers.insert(0, 'hub')
print(rivers)
print(rivers[0])

print("The first three items in the list are:")
print(rivers[0:3])
print("Three items from the middle of the list are:")
print(rivers[1:4])
print("The last three items in the list are:")
print(rivers[2:5])