places_i_would_like_to_visit = ['disneyland', 'fairy_meadows', 'switzerland', 'mecca', 'japan']
print(f"Here is the list of places i would like to visit in it's original order:\n {places_i_would_like_to_visit}")
print(f"\nHere is the list in alphabetical order, although i've only changed it temporarily:\n {sorted(places_i_would_like_to_visit)}")
print(f"\nLook! It's back to normal: {places_i_would_like_to_visit}")
print(f"\nHere is the list in reverse alphabetical order, temporarily changed:\n {sorted(places_i_would_like_to_visit, reverse = True)}")
print(f"\nAand....it's back to normal!:\n {places_i_would_like_to_visit}")
places_i_would_like_to_visit.reverse()
print(f"\nGagh?! I accidentally reversed the chronological order of the list:\n {places_i_would_like_to_visit}")
places_i_would_like_to_visit.reverse()
print(f"\n'sigh' It's back to normal:\n {places_i_would_like_to_visit}")
places_i_would_like_to_visit.sort()
print(f"\nHaHa! I changed it to alphabetical order..wait what?! NO, it changed permanantly:\n {places_i_would_like_to_visit}")
places_i_would_like_to_visit.sort(reverse = True)
print(f"\nI think i fixed it...damn it! It's in reverse alphabetical order now:\n {places_i_would_like_to_visit}")
print(f"\n I'm done. Nope. I'm not bothering with this anymore. (door closing sound)")