# Generated by Django 4.0.6 on 2022-07-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='date',
            new_name='date_added',
        ),
    ]
